services:
  app:
    build: .
    volumes:
      - .:/app
      - ./server/ssh/ssh_client_rsa_key:/etc/secret-volume/id_rsa:ro
    env_file:
      - env.development

  fileserver:
    image: 'atmoz/sftp'
    volumes:
      - ./server/files:/home/my_user/files
      - ./server/ssh/ssh_client_rsa_key.pub:/home/my_user/.ssh/keys/id_rsa.pub:ro
      - ./server/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./server/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: my_user::1001
