name: Run Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0, 3.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Bundle install
      run: bundle install
    - name: Run linter for Ruby
      run: bundle exec standardrb
    - name: Run tests
      run: bundle exec rspec
